import fs from "node:fs/promises";
import path from "node:path";

export const TOP_TIER_COMBINED_RANK = "Grandmaster/Champion";
export const LEGACY_TOP_TIER_RANKS = ["Grandmaster", "Champion"];

export const RANKS = [
  "All",
  "Bronze",
  "Silver",
  "Gold",
  "Platinum",
  "Diamond",
  "Master",
  TOP_TIER_COMBINED_RANK,
];

const HERO_NAME_ALIASES = new Map([
  ["D.VA", ["D.VA", "D.Va", "DVA"]],
  ["Cassidy", ["Cassidy", "McCree", "Mccree"]],
  ["Soldier: 76", ["Soldier: 76", "Soldier 76"]],
  ["Lucio", ["Lucio", "Lúcio"]],
  ["Torbjorn", ["Torbjorn", "Torbjörn"]],
  ["Wrecking Ball", ["Wrecking Ball", "Hammond"]],
]);

const LEGACY_IMAGE_SLUGS = new Map([
  ["Cassidy", "mccree"],
  ["D.VA", "dva"],
  ["Soldier: 76", "soldier76"],
  ["Wrecking Ball", "wreckingball"],
  ["Junker Queen", "junker-queen"],
]);

const CONTROL_PREFIX_MAP = [
  "Antarctic Peninsula",
  "Busan",
  "Ilios",
  "Lijiang Tower",
  "Nepal",
  "Oasis",
  "Samoa",
];

export function repoPath(...segments) {
  return path.join(process.cwd(), ...segments);
}

export async function readJson(filePath) {
  return JSON.parse(await fs.readFile(filePath, "utf8"));
}

export async function writeJson(filePath, data) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

export async function writeBrowserDataBundle(filePath, payload) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const serialized = JSON.stringify(payload, null, 2);
  const contents = [
    "/* Auto-generated by scripts/update-overwatch-data.mjs */",
    "window.__OW_DATA__ = Object.freeze(",
    serialized,
    ");",
    "",
  ].join("\n");
  await fs.writeFile(filePath, contents, "utf8");
}

export function heroKey(name) {
  return String(name ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]/g, "");
}

export function getHeroNameCandidates(name) {
  const defaults = [name];
  const alias = HERO_NAME_ALIASES.get(name) ?? [];
  return [...new Set([...defaults, ...alias])];
}

export function slugify(value) {
  return String(value ?? "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function heroImageSlug(heroName) {
  if (LEGACY_IMAGE_SLUGS.has(heroName)) {
    return LEGACY_IMAGE_SLUGS.get(heroName);
  }
  return slugify(heroName);
}

export function mapToCategory(roleName) {
  const role = String(roleName ?? "").toLowerCase();
  if (role.includes("tank")) return "Tank";
  if (role.includes("support")) return "Support";
  if (role.includes("damage") || role.includes("dps")) return "DPS";
  return "DPS";
}

export function canonicalizeMapName(localMapName) {
  for (const prefix of CONTROL_PREFIX_MAP) {
    if (localMapName.startsWith(prefix)) {
      return prefix;
    }
  }
  return localMapName;
}

export function mapToRatesSlug(mapName) {
  if (!mapName || mapName === "All") return "all-maps";
  return slugify(mapName);
}

export function parsePercent(value) {
  if (typeof value === "number") return value;
  if (typeof value !== "string") return Number.NaN;
  return Number.parseFloat(value.replace(",", "."));
}

export function unique(values) {
  return [...new Set(values)];
}

export function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export function formatIsoNow() {
  return new Date().toISOString();
}

export function ensureFiniteNumber(value, fallback = null) {
  return Number.isFinite(value) ? value : fallback;
}

export function normalizeTierNameForRates(rank) {
  if (rank === TOP_TIER_COMBINED_RANK) return "Grandmaster";
  if (rank === "Champion") return "Grandmaster";
  return rank === "All" ? "All" : rank;
}
